# 汉化参考：https://gitee.com/ifaxin/eureka-server-hans
server:
  port: 8761
  use-forward-headers: true
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root

eureka:
  server:
    # false表示eureka服务器关闭自我保护模式
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
    # eureka-server注册使用真实ip
    prefer-ip-address: true
  client:
    # 是否将自己注册到服务中心，默认为true
    register-with-eureka: false
    # 是否从服务中心获取注册信息，默认为true
    fetch-registry: false
    # 注册中心地址
    service-url:
      # 设置与eureka-server交互的地址，默认为http://127.0.0.1:8761/eureka/，多个地址用逗号（,）分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/