# 汉化参考：https://gitee.com/ifaxin/eureka-server-hans
server:
  use-forward-headers: true
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  application:
    name: eureka-server
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    user:
      name: root
      password: root

eureka:
  server:
    # false表示eureka服务器关闭自我保护模式
    enable-self-preservation: false
    # eureka server清理无效节点的时间间隔
    eviction-interval-timer-in-ms: 5000
  client:
    # 是否将自己注册到服务中心，默认为true
    register-with-eureka: false
    # 是否从服务中心获取注册信息，默认为true
    fetch-registry: false

---
server:
  port: 8001

spring:
  profiles:
    active: eureka1

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://root:root@eureka2:8002/eureka/,http://root:root@eureka3:8003/eureka/

---
server:
  port: 8002

spring:
  profiles:
    active: eureka2

eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://root:root@eureka1:8001/eureka/,http://root:root@eureka3:8003/eureka/

---
server:
  port: 8003

spring:
  profiles:
    active: eureka3

eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://root:root@eureka1:8001/eureka/,http://root:root@eureka2:8002/eureka/