server:
  port: 8010
  use-forward-headers: true
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  application:
    name: boot-admin-server
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    # 服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://127.0.0.1:${server.port}/
    # 解决/actuator/health（401 Unauthorized)
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  client:
    # 表示eureka client间隔多久拉取服务注册信息
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://root:root@127.0.0.1:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS
