spring:
  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  instance:
    # 服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10
    status-page-url: http://127.0.0.1:${server.port}/
  client:
    # 表示eureka client间隔多久拉取服务注册信息
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://root:root@127.0.0.1:8001/eureka/

logging:
  level:
    root: info
    org.springframework.cloud.gateway: info
